version: "3.8"
services:
  redis:
    image: redis:6.2.2
    container_name: redis
    restart: unless-stopped 
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/data
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    hostname: mysql
    image: mysql:5.7.26
    container_name: mysql
    restart: unless-stopped 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    environment:
      - TZ=Asia/Shanghai 
      - MYSQL_ROOT_PASSWORD=123456 
    volumes:
       - /etc/localtime:/etc/localtime:ro 
       - ./data/mysql/data:/var/lib/mysql/data 
       - ./conf/mysql/my.cnf:/etc/mysql/my.cnf 
    ports:
        - "3306:3306"

  zookeeper:
    image: zookeeper:3.4
    restart: always
    container_name: zookeeper
    volumes:
      - ./conf/zookeeper/zoo.cfg:/conf/zoo.cfg
      - ./data/zookeeper/data:/zk_data
      - ./data/zookeeper/logs:/zk_logs
    ports: 
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    container_name: kafka
    restart: unless-stopped 
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  hbase:
    image: harisekhon/hbase:1.3
    hostname: cloud
    container_name: hbase
    restart: unless-stopped 
    ports:
      - 18080:8080
      - 18085:8085 
      - 19090:9090
      - 19095:9095
      - 16000:16000
      - 16010:16010 
      - 16201:16201 
      - 16301:16301
      - 16020:16020
      - 16030:16030
      - 2182:2181 # ! ! 
    volumes:
      - ./data/hbase/data:/hbase-data

  canal:
    image: canal/canal-server:v1.1.4
    container_name: canal
    restart: unless-stopped 
    #    ports:
    # - 11111:11111
    network_mode: "host"
    environment:
      - canal.auto.scan=false
      - canal.instance.master.address=127.0.0.1:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=123456
      - canal.instance.filter.regex=.*\\..*
      - canal.destinations=test
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
    volumes:
      - ./data/canal/data:/admin/canal-server
  
  # port : 9090
  prometheus: 
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # port : 9100
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.7.0
    restart: always
    privileged: true
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:6.7.0
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_URL: http://127.0.0.1:9200
    ports:
      - 5601:5601
